name: Deployment Test 
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."
